name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend-react-build:
    name: Frontend (React) Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./procumentplatform/frontend-react
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: procumentplatform/frontend-react/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-react-dist
          path: procumentplatform/frontend-react/dist

  backend-build:
    name: Backend Build & Publish
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./procumentplatform/backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore vw-procurement-backend.sln

      - name: Build (Release)
        run: dotnet build vw-procurement-backend.sln --no-restore -c Release

      # There are no unit test projects currently; keep a placeholder for future tests
      #- name: Test
      #  run: dotnet test vw-procurement-backend.sln --no-build -c Release --verbosity normal

      - name: Publish API
        run: dotnet publish VWProcurement.API/VWProcurement.API.csproj -c Release -o VWProcurement.API/publish

      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-api-publish
          path: procumentplatform/backend/VWProcurement.API/publish